M9BR-5338: Removed instrumentation load as it caused issues.
IncompatibleClassChangeError: class java/util/EnumMap has
conflicting defaults for method putIfAbsent
Fixed pom.xml, removed parent and added group instead